### ISSUE TITLE
Unable to get program list

### ISSUE THREAD

**Issue by karoria** [cncjs/cncjs-shopfloor-tablet#10]
@MitchBradly
Sir, I am unable to get the program list using shopfloor tablet. I doubt if i missed any process to configure watch directory. I have manually created a directory named "watch" under home/pi
Kindly guide me.

**Comment by MitchBradley** [comment]
You must add a "watchDirectory" line inside the .cncrc file, inside the braces, like this:

```
{
    "watchDirectory": "/home/pi/watch",

```
followed by whatever was already in that file

**Comment by karoria** [comment]
Got it. Thanks a lot. One more question.. Can I change default feed values of buttons (0.001 to 5) on shopfloor pendant simply by editing html code or it requires some workaround in js? As I work in mm, those values are too small to work.

**Comment by MitchBradley** [comment]
Yes, it's just HTML.  In src/index.html there are a bunch of sections like:

```
                    <button
                        type="button"
                        class="btn btn-default set-distance"
                        title="Jog by 0.5"
                        onclick="cnc.setDistance('0.5')"
                    >
                        0.5
                    </button>
```

Just change the numbers per your needs.

**Comment by karoria** [comment]
Many thanks :)
